targets:
  $default:
    builders:
      pigeon_generator:
        options:
          dart:
            out: "lib/src/pigeons"
          out_folder: "pigeons"

additional_public_assets:
  - pigeons/**
