name: file_flow
version: 1.0.0-dev.2
description: "Seamlessly handle background file uploads and downloads, with support for multiple platforms."
homepage: https://github.com/melvinotieno/file_flow
repository: https://github.com/melvinotieno/file_flow
issue_tracker: https://github.com/melvinotieno/file_flow/issues
documentation: https://github.com/melvinotieno/file_flow/blob/main/README.md

topics:
  - file-upload
  - file-download
  - background-upload
  - background-download

environment:
  sdk: ^3.7.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  logging: ^1.3.0
  uuid: ^4.5.1

dev_dependencies:
  build_runner: ^2.4.15
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  pigeon: ^22.7.4
  pigeon_generator: ^2.0.6

flutter:
  plugin:
    platforms:
      android:
        package: com.melvinotieno.file_flow
        pluginClass: FileFlowPlugin
