// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, unnecessary_import, no_leading_underscores_for_local_identifiers
// ignore_for_file: avoid_relative_lib_imports
import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;
import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';
import 'package:flutter_test/flutter_test.dart';

import 'package:file_flow/src/pigeons/flow.g.dart';


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is StorageDirectory) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    }    else if (value is TaskType) {
      buffer.putUint8(130);
      writeValue(buffer, value.index);
    }    else if (value is TaskState) {
      buffer.putUint8(131);
      writeValue(buffer, value.index);
    }    else if (value is TaskErrorCode) {
      buffer.putUint8(132);
      writeValue(buffer, value.index);
    }    else if (value is TaskException) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    }    else if (value is TaskProgressData) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    }    else if (value is TaskResumeData) {
      buffer.putUint8(135);
      writeValue(buffer, value.encode());
    }    else if (value is TaskCompleteData) {
      buffer.putUint8(136);
      writeValue(buffer, value.encode());
    }    else if (value is Task) {
      buffer.putUint8(137);
      writeValue(buffer, value.encode());
    }    else if (value is TaskStatus) {
      buffer.putUint8(138);
      writeValue(buffer, value.encode());
    }    else if (value is TaskProgress) {
      buffer.putUint8(139);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129: 
        final int? value = readValue(buffer) as int?;
        return value == null ? null : StorageDirectory.values[value];
      case 130: 
        final int? value = readValue(buffer) as int?;
        return value == null ? null : TaskType.values[value];
      case 131: 
        final int? value = readValue(buffer) as int?;
        return value == null ? null : TaskState.values[value];
      case 132: 
        final int? value = readValue(buffer) as int?;
        return value == null ? null : TaskErrorCode.values[value];
      case 133: 
        return TaskException.decode(readValue(buffer)!);
      case 134: 
        return TaskProgressData.decode(readValue(buffer)!);
      case 135: 
        return TaskResumeData.decode(readValue(buffer)!);
      case 136: 
        return TaskCompleteData.decode(readValue(buffer)!);
      case 137: 
        return Task.decode(readValue(buffer)!);
      case 138: 
        return TaskStatus.decode(readValue(buffer)!);
      case 139: 
        return TaskProgress.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}
