// Autogenerated from Pigeon (v22.7.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.melvinotieno.file_flow.pigeons

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer

private fun wrapResult(result: Any?): List<Any?> {
  return listOf(result)
}

private fun wrapError(exception: Throwable): List<Any?> {
  return if (exception is FlowFlutterError) {
    listOf(
      exception.code,
      exception.message,
      exception.details
    )
  } else {
    listOf(
      exception.javaClass.simpleName,
      exception.toString(),
      "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
    )
  }
}

private fun createConnectionError(channelName: String): FlowFlutterError {
  return FlowFlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlowFlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/** */
enum class StorageDirectory(val raw: Int) {
  APPLICATION_DOCUMENTS(0),
  DOWNLOADS(1);

  companion object {
    fun ofRaw(raw: Int): StorageDirectory? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** The type of a task. */
enum class TaskType(val raw: Int) {
  /** Task is a download task. */
  DOWNLOAD(0),
  /** Task is an upload task. */
  UPLOAD(1);

  companion object {
    fun ofRaw(raw: Int): TaskType? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** The state of a task. */
enum class TaskState(val raw: Int) {
  /** Task is pending. */
  PENDING(0),
  /** Task is running. */
  RUNNING(1),
  /** Task is paused. */
  PAUSED(2),
  /** Task has completed successfully. */
  COMPLETED(3),
  /** Task has failed. */
  FAILED(4),
  /** Task has been canceled. */
  CANCELED(5);

  companion object {
    fun ofRaw(raw: Int): TaskState? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class TaskProgress (
  val progress: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): TaskProgress {
      val progress = pigeonVar_list[0] as Long
      return TaskProgress(progress)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      progress,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class TaskStatus (
  val state: TaskState
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): TaskStatus {
      val state = pigeonVar_list[0] as TaskState
      return TaskStatus(state)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      state,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class Task (
  val id: String,
  val url: String,
  val method: String,
  val headers: Map<String, String>,
  val timeout: Long,
  val proxyAddress: String? = null,
  val proxyPort: Long? = null,
  val filename: String? = null,
  val directory: String? = null,
  val baseDirectory: StorageDirectory,
  val type: TaskType
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): Task {
      val id = pigeonVar_list[0] as String
      val url = pigeonVar_list[1] as String
      val method = pigeonVar_list[2] as String
      val headers = pigeonVar_list[3] as Map<String, String>
      val timeout = pigeonVar_list[4] as Long
      val proxyAddress = pigeonVar_list[5] as String?
      val proxyPort = pigeonVar_list[6] as Long?
      val filename = pigeonVar_list[7] as String?
      val directory = pigeonVar_list[8] as String?
      val baseDirectory = pigeonVar_list[9] as StorageDirectory
      val type = pigeonVar_list[10] as TaskType
      return Task(id, url, method, headers, timeout, proxyAddress, proxyPort, filename, directory, baseDirectory, type)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      url,
      method,
      headers,
      timeout,
      proxyAddress,
      proxyPort,
      filename,
      directory,
      baseDirectory,
      type,
    )
  }
}
private open class FlowPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          StorageDirectory.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          TaskType.ofRaw(it.toInt())
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          TaskState.ofRaw(it.toInt())
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          TaskProgress.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          TaskStatus.fromList(it)
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          Task.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is StorageDirectory -> {
        stream.write(129)
        writeValue(stream, value.raw)
      }
      is TaskType -> {
        stream.write(130)
        writeValue(stream, value.raw)
      }
      is TaskState -> {
        stream.write(131)
        writeValue(stream, value.raw)
      }
      is TaskProgress -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is TaskStatus -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      is Task -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface FileFlowHostApi {
  fun enqueue(task: Task): Boolean
  fun pause(taskId: String): Boolean
  fun resume(taskId: String): Boolean

  companion object {
    /** The codec used by FileFlowHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      FlowPigeonCodec()
    }
    /** Sets up an instance of `FileFlowHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: FileFlowHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.file_flow.FileFlowHostApi.enqueue$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val taskArg = args[0] as Task
            val wrapped: List<Any?> = try {
              listOf(api.enqueue(taskArg))
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.file_flow.FileFlowHostApi.pause$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val taskIdArg = args[0] as String
            val wrapped: List<Any?> = try {
              listOf(api.pause(taskIdArg))
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.file_flow.FileFlowHostApi.resume$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val taskIdArg = args[0] as String
            val wrapped: List<Any?> = try {
              listOf(api.resume(taskIdArg))
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
class FileFlowFlutterApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by FileFlowFlutterApi. */
    val codec: MessageCodec<Any?> by lazy {
      FlowPigeonCodec()
    }
  }
  fun onProgress(taskIdArg: String, progressArg: Long, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.file_flow.FileFlowFlutterApi.onProgress$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(taskIdArg, progressArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlowFlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
}
